### DISCUSSION TITLE
[Script request] Zurg

### DISCUSSION THREAD

**Discussion by jensbodal** [community-scripts/ProxmoxVE#1119] [Request script]
### Application Name

Zurg

### Website

https://github.com/debridmediamanager/zurg-testing

### Description

Originally requested by @novajolt (https://github.com/tteck/Proxmox/discussions/2670)

> A self-hosted Real-Debrid webdav server written from scratch. Together with [rclone](https://rclone.org/) it can mount your Real-Debrid torrent library into your file system like Dropbox. It's meant to be used with Infuse (webdav server) and Plex (mount zurg webdav with rclone).

ElfHosted also has a good description of what it does: https://docs.elfhosted.com/app/zurg/

I'm not familiar enough with Zurg/Rclone to have a recommendation, I was going to set this up to see how it works and there are existing docker setups and guides for alternative methods. 

### Due Diligence

- [X] I have searched existing [scripts](https://community-scripts.github.io/Proxmox/scripts) and found no duplicates.
- [X] I have searched existing [discussions](https://github.com/community-scripts/ProxmoxVE/discussions?discussions_q=) and found no duplicate requests.
- [X] This is not a game-related request.

**Comment by jensbodal** [comment]
So from what I found it's difficult to "share" the rclone mounts directly without adding another layer on top since they are FUSE mounts.  I tried setting up a [shared mount point](https://blog.kye.dev/proxmox-zfs-mounts) but that does not work with a FUSE mount. For now I decided to just run rclone on the same LXC that I run Plex, as Plex can read the FUSE mount just fine. Rclone connects to the container I am running Zurg in and this is working mostly fine, but some additional setup is needed I believe to ensure proper boot order as Plex at some point couldn't find the files on the rclone mount.  

What I have setup now but have not yet verified is to set the proxmox boot order to ensure plex comes up after zurg, and then within the plex LXC services ensure the plex service comes up after the rclone service.

There's more to all of this but here's the files I am using with this working.

---

The following used the base files from `zurg-testing` along with other settings I found from some research. I'm not claiming these to be entirely necessary or "correct", but they _are_ working for my setup which allows me to stream movies from RD to Plex on any device I can run Plex on. I was able to play a 4k movie (that plex then transcodes) to a mobile phone over 4G internet. 

* [zurg/config.yml](https://github.com/debridmediamanager/zurg-testing/blob/main/config.yml)
* [rclone/rclone.config](https://github.com/debridmediamanager/zurg-testing/blob/main/rclone.conf)
* [systemd/system/*.service](https://github.com/debridmediamanager/zurg-testing/tree/main/lib/systemd/system)
* [plex_update.sh](https://github.com/debridmediamanager/zurg-testing/blob/main/scripts/plex_update.sh) (haven't gotten this working yet but it's **not** *needed*, plus I am pretty sure there's a better way to notify Plex to look for changes)

## zurg

**config.yml**


```
zurg: v1
token: "<YOUR_TOKEN>"

# I don't know what this does as the directory is empty
# JSON files are populated at $CWD/data
# I assume this has something to do with separate settings 
# related to actually downloading the files instead of streaming them?
download_dir: "/mnt/zurg" 

# This file _is_ written to but there are also logs in the $CWD/logs directory
log_file: "/var/log/zurg.log"

enable_repair: true
auto_delete_rar_torrents: true
# I don't have this working yet but I haven't looked at it at all yet
# Right now things just eventually show up in plex or I can refresh manually 
# on_library_update: sh /opt/zurg/plex_update.sh "$@"

# Action for RAR files: extract, delete, or none (default: "none")
rar_action: none

# If a torrent contains any file with these extensions, delete the torrent
delete_torrent_if_extensions_found:
  - zipx
  - rar

# Additional file extensions to consider as playable
# This is definitely not needed for the basic setup but I was messing around with what this can support
addl_playable_extensions:
  - m3u

directories:
  shows:
    group_order: 20
    group: media
    filters:
      - has_episodes: true

  movies:
    group_order: 30
    group: media
    only_show_the_biggest_file: true
    filters:
      - regex: /.*/
```

**zurg.service**

```
[Unit]
Description=Zurg Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=LOG_LEVEL=info
ExecStart=/opt/zurg/zurg -c /opt/zurg/config.yml
WorkingDirectory=/opt/zurg/
StandardOutput=file:/var/log/zurg.log
StandardError=file:/var/log/zurg.log
Restart=on-abort
RestartSec=1
StartLimitInterval=600s
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
```

With this I know have a zurg webdev server running at `zurg:9999`

## Rclone / Plex

The only change I made in plex was just adding the `/mnt/zurg/movies` and `/mnt/zurg/shows` folders to my Movies and TV Shows libraries in plex. These folders are available after setting up Rclone to mount the zurg webdev folders as FUSE mounts. I also added a dependency on the rclone service to the plex service using their overrides syntax, and so far I haven't seen the issue again where plex can't find the files, but I'm not confident that that issue is gone now since I have only tested it out today.

**rclone.conf**

```
[zurg]
type = webdav
url = http://zurg:9999/dav
vendor = other
pacer_min_sleep = 0
```

**rclone.service**

```
[Unit]
Description=Rclone mount for zurg
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
StandardOutput=file:/var/log/rclone.log
StandardError=file:/var/log/rclone.log
ExecStart=/opt/rclone/rclone mount zurg: /mnt/zurg      \
  --read-only                                           \
  --log-level=INFO                                      \
  --allow-non-empty                                     \
  --allow-other                                         \
  --attr-timeout 10y                                    \
  --dir-cache-time 60s                                  \
  --vfs-cache-mode full                                 \
  --vfs-refresh                                         \
  --vfs-read-chunk-size 2M                              \
  --vfs-read-chunk-size-limit 64M                       \
  --buffer-size 128M                                    \
  --vfs-read-ahead 128M                                 \
  --vfs-cache-poll-interval 30s                         \
  --vfs-fast-fingerprint                                \
  --vfs-cache-max-age 2M                                \
  --vfs-cache-max-size 2G                               \
  --vfs-cache-min-free-space 512M                       \
  --vfs-disk-space-total-size 4G                        \
  --transfers 16                                        \
  --checkers 16                                         \
  --multi-thread-streams 4                              \
  --vfs-read-wait 40ms                                  \
  --config=/opt/rclone/rclone.conf                      \
  --log-file=/opt/rclone/rclone.log                     \
  --cache-dir=/opt/rclone/cache

# ExecStop command to unmount the Rclone mount safely
ExecStop=/bin/bash -c '/bin/fusermount -uz /mnt/zurg; umount /mnt/zurg'

# Restart policy matching Docker's 'restart: unless-stopped'
Restart=unless-stopped
RestartSec=5

# Limit the start attempts to prevent rapid restarts
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
```

**/etc/systemd/system/plexmediaserver.service.d/override.conf**

```
[Unit]
After=rclone.service
```
