### DISCUSSION TITLE
Prometheus Proxmox VE

### DISCUSSION THREAD

**Discussion by daschmidt1994** [community-scripts/ProxmoxVE#2867] [Q&A] [answered]
Good evening,

I have the Prometheus Proxmox VE installed and config.
With the url http://192.168.178.203:9221/pve?target=192.168.178.188 I can see the metrics.
But when I add the config in the prometheus lxc:
`  - job_name: 'PVE'
    static_configs:
      - targets: ["192.168.178.203:9221"]
    metrics_path: /pve
    params:
      module: [default]`

I get this error: Error scraping target: server returned HTTP status 500 INTERNAL SERVER ERROR

**Comment by tremor021** [comment]
Because targets: ["192.168.178.203:9221"] is your server? In the url target is some other IP

**Reply by daschmidt1994** [reply]
192.168.178.203 is the ip where the Prometheus Proxmox VE Exporter LXC is running
192.168.178.188 is the ip from my proxmox host

When I have Prometheus Proxmox VE running I also have a LXC with promotheus where I add the scraper config

**Comment by towerhand** [comment]
Would you mind sharing your pve.yml?

**Reply by daschmidt1994** [reply]
`default:
    user: prometheus@pam
    token_name: "prometheus"
    token_value: "f71fd6c6-5c9c-4eb5-bcb1-edaa7c921c73"
    verify_ssl: false`

**Reply by towerhand** [reply]
Thank you. For some reason I can't get mine to even show the metrics.

**Comment by daschmidt1994** [comment]
can nobody help?

**Comment by MickLesk** [comment]
maybe: @andygrunwald

**Reply by andygrunwald** [reply]
Tanks for tagging @MickLesk. I posted a bit of help below.

**Comment by andygrunwald** [comment, marked as answer]
@daschmidt1994 Here is my Prometheus Scrape Configuration that works as expected:

```yaml
  # Prometheus Proxmox VE exporter
  - job_name: 'prometheus-proxmox-ve-exporter'
    static_configs:
      - targets: ['192.168.178.61'] # Proxmox VE node
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.178.62:9221  # PVE exporter
```

This one is documented here: https://github.com/prometheus-pve/prometheus-pve-exporter?tab=readme-ov-file#prometheus-configuration

@towerhand Here is my pve.yml that works as expected:

```yaml
default:
  user: prometheus@pve
  password: "my-password"
  verify_ssl: false
```

This requires a user in Proxmox. Documented here: https://github.com/prometheus-pve/prometheus-pve-exporter?tab=readme-ov-file#prometheus-configuration

Does this help ?
