### DISCUSSION TITLE
[Script Request] Outline

### DISCUSSION THREAD

**Discussion by krstivoja** [community-scripts/ProxmoxVE#342] [Request script] [answered]
Hi There!

Would love to see a script developed for Outline Wiki (https://github.com/outline/outline).

Sadly i am not Linux orientated enough to get this up and running! I feel that their documentation is not detailed enough or they expect someone of quite significant Linux proficiency but sadly that isn't me haha.

**Comment by Aloe-recite** [comment]
Adding my vote! This has been on my mind for a while, seems great although not exactly a one-clic installation indeed, not sure if a script might support the setup since AFAIK you *need* to setup login through Google or Github or such identity providers so maybe it's not feasible or not a 1-click install solution...

**Reply by krstivoja** [reply]
I think you just need to pass SMTP settings

**Reply by burgerga** [reply]
It's definitely complicated, because in addition to seemingly simple instructions at https://docs.getoutline.com/s/hosting/doc/from-source-BlBxrNzMIP, you indeed need to setup an identity provider (not smtp, but one of https://docs.getoutline.com/s/hosting/doc/authentication-7ViKRmRY5o), ~but also a s3-compatible storage solution (e.g., minio) to enable the upload of images~ (I see [local file storage is supported](https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7) now). Overall the documentation is very docker minded

**Reply by Aloe-recite** [reply]
I did a quick test with docker and it wans't exactly easy that way either. But I wans't paying much attention admittedly. Will have to try again sometimes. This is exactyl the kind of application that I wouldn't want on docker but on a separate container, since it will be externally acessible, collaborative, etc.

**Reply by krstivoja** [reply]
I can share my docker / env setup if that would help also runtipi have setup. Maybe that could be a start?

**Reply by Aloe-recite** [reply]
@krstivoja thanks, seeing a working an real-life tested docker-compose would be a great help and start!

**Reply by burgerga** [reply]
I posted my first attempt at a script below :)

**Comment by burgerga** [comment]
Ok, I spent some time on this, and it is indeed complicated, some notes:
* The script below can be copy pasted in a Ubuntu 24.04 LXC and will result in a working outline (I combined some stuff from existing community scripts, mainly redis and linkwarden) EDIT: also works on Debian 12 now
* LXC settings: 8GB hard disk (without any documents will already be 4.5GB), 4GB RAM (will run out of memory with 2GB during building), 2 cores 
* Some environment variables already need to be set (the script already does this) before the `yarn sequelize` commands, because it needs some of them to setup the database, this includes the `URL` env var (which is annoying because this is user input and will make a community script a bit more tricky)
* The below script will not work with node 16 (contrary to https://docs.getoutline.com/s/hosting/doc/from-source-BlBxrNzMIP); when using node 16 I got the message that only node >=18, <=20 was supported, so I went with 20
* ~Setting `NODE_ENV="production"` will cause an error in `yarn build` with ..., surprisingly, setting `NODE_ENV="development"` also fails, you have to omit `NODE_ENV` completely (if you want to try setting `NODE_ENV`, also uncomment the line that creates the entry in the `/opt/outline/.env` file)~ -> Solved with help from Tom Moor from Outline (https://github.com/outline/outline/discussions/8008#discussioncomment-11354747): build with "development", run with "production" -> script updated accordingly

When the script is done:
* Use a reverse proxy to point https `URL` to your instance (IP:3000) 
* If you are successful, you will get a "Login to Outline" window WITHOUT any buttons/fields, this is because it still needs an Identity Provider, see https://github.com/outline/outline/blob/main/.env.sample (I tested it with OIDC using Authentik, and it worked fine). Add it to the `/opt/outline/.env` file and run `systemctl restart outline`.

And now finally the script (don't forget to change the URL):
```bash
URL="https://outline.your.domain"

apt-get install -y \
  sudo \
  lsb-release \
  postgresql \
  gnupg \
  git

mkdir -p /etc/apt/keyrings

NODE_MAJOR=20
wget -qO- https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" >/etc/apt/sources.list.d/nodesource.list

wget -qO- https://packages.redis.io/gpg | gpg --dearmor -o /etc/apt/keyrings/redis-archive-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" >/etc/apt/sources.list.d/redis.list

apt-get update

apt-get install -y nodejs
npm install -g yarn

apt-get install -y redis
sed -i 's/^bind .*/bind 0.0.0.0/' /etc/redis/redis.conf
systemctl enable -q --now redis-server.service

git clone --depth 1 --branch v0.81.1 https://github.com/outline/outline.git /opt/outline
cd /opt/outline

# Instructions outline website

## First do CONFIGURATION

SECRET_KEY="$(openssl rand -hex 32)"
UTILS_SECRET="$(openssl rand -hex 32)"

DB_NAME=outlinedb
DB_USER=outline
DB_PASS="$(openssl rand -base64 18 | tr -d '/' | cut -c1-13)"
DATABASE_URL="postgres://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"
REDIS_URL=redis://localhost:6379
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data

mkdir -p $FILE_STORAGE_LOCAL_ROOT_DIR

sudo -u postgres psql -c "CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASS';"
# Give user permission to create dbs
sudo -u postgres psql -c "ALTER ROLE $DB_USER WITH CREATEDB;"
# Copied from linkwarden setup, not sure what these do
sudo -u postgres psql -c "ALTER ROLE $DB_USER SET client_encoding TO 'utf8';"
sudo -u postgres psql -c "ALTER ROLE $DB_USER SET default_transaction_isolation TO 'read committed';"
sudo -u postgres psql -c "ALTER ROLE $DB_USER SET timezone TO 'UTC';"

{
    echo "Outline-Credentials"
    echo "Outline Database User: $DB_USER"
    echo "Outline Database Password: $DB_PASS"
    echo "Outline Database Name: $DB_NAME"
    echo "Outline Secret: $SECRET_KEY"
    echo "Outline Utils Secret: $UTILS_SECRET"
} >> ~/outline.creds

## Continue installation, first build in development
yarn install --no-optional --frozen-lockfile && yarn cache clean && yarn build

## Continue in production
rm -rf ./node_modules
yarn install --production=true--frozen-lockfile && yarn cache clean

env_path="/opt/outline/.env"
{
    echo "NODE_ENV=production"
    echo "SECRET_KEY=$SECRET_KEY"
    echo "UTILS_SECRET=$UTILS_SECRET"
    echo "DATABASE_URL=$DATABASE_URL"
    echo "REDIS_URL=$REDIS_URL"
    echo "URL=$URL"
    echo "FILE_STORAGE=local"
    echo "FILE_STORAGE_LOCAL_ROOT_DIR=$FILE_STORAGE_LOCAL_ROOT_DIR"
    echo "WEB_CONCURRENCY=2"
} >$env_path

# set env based on env file
export $(grep -v '^#' $env_path | xargs -d '\n')

yarn sequelize db:create 
yarn sequelize db:migrate

cat <<EOF >/etc/systemd/system/outline.service
[Unit]
Description=Outline Service
After=network.target

[Service]
Type=exec
EnvironmentFile=/opt/outline/.env
WorkingDirectory=/opt/outline
ExecStart=/usr/bin/yarn start

[Install]
WantedBy=multi-user.target
EOF
systemctl enable -q --now outline.service
```

**Reply by krstivoja** [reply]
@burgerga when i created it with Dockge or runtipi i had problem to upload files. 

Check this one: https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7


If you get permissions errors writing files, ensure that Outline has permission to write to the directory, by giving the user ID access: chown 1001 /location/on/host/filesystem

**Reply by burgerga** [reply]
Not an issue here since outline runs as root in the LXC

**Reply by burgerga** [reply]
I got feedback from the Outline team, and made some changes, everything works as expected now! See the notes at the top for the changes.

**Reply by Aloe-recite** [reply]
@burgerga stupid question: how to make you script...a script? should I just create the file in the LXC and chmod +X it?

**Reply by krstivoja** [reply]
Nice one! Thanks for the update!

**Reply by burgerga** [reply]
@Aloe-recite what I did so far is creating the Ubuntu or Debian LXC using the community scripts, and then just copy paste the whole thing in and pressing Enter 😀 (after changing the URL of course)

**Reply by Aloe-recite** [reply]
Installation took a while but went fine apparently! One question though: I used a url which I intend to manage through a Cloudflare tunnel protected with zero access. In the tunnel hostname server, where should I point? Port 80 of the container? http://192.168.1.XXX:80 is not working, https and 443 neither :( 
NEVERMIND I just noticed that the port is 3000, Shame on me!

**Reply by burgerga** [reply]
I should probably make that clearer :)

**Reply by krstivoja** [reply]
Outline run on port:
```
ports:
      - 3000:3000
```
      
But you need to run it on the provided link:
```
URL="https://outline.your.domain"
```

**Reply by Aloe-recite** [reply]
thanks guys! I just discovered that personal Gmail is not allowed, Github doesn't seem to work (I am not capable of configuring it, plus the instructions say that "at least ONE OF EITHER Google, Slack, or Microsoft is required for a working installation or you'll have no sign-in options" which is strange since there are plenty of other alternatives in the file, and also generic oidc. I don't know why they don't offer a clear guide but ok... I can understand that they want to leave self hosting to real techies and direct everyone else to the paid hosted solution :)

**Reply by burgerga** [reply]
Yeah the instructions are outdated, I'm using OIDC (via Authentik) and it's working like a charm. Google will likely also work, but you probably need https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid (it's a bit of work)

**Reply by burgerga** [reply]
Wrote a pull request that will add this to the community scripts repo: https://github.com/community-scripts/ProxmoxVE/pull/472

**Comment by krstivoja** [comment]
Compose .yaml

```yaml

version: "3.2"
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline-app
    hostname: outline-app
    ports:
      - 3000:3000
    volumes:
      - ./storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    environment:
      PGSSLMODE: disable
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      URL: ${URL}
      PORT: ${PORT}
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 26214400
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # SMTP Configuration
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_REPLY_EMAIL: ${SMTP_REPLY_EMAIL}
      SMTP_TLS_CIPHERS: ${SMTP_TLS_CIPHERS}
      SMTP_SECURE: ${SMTP_SECURE}
    restart: unless-stopped
  redis:
    container_name: outline-redis
    hostname: outline-redis
    image: redis
    volumes:
      - ./redis.conf:/redis.conf
    command:
      - redis-server
      - /redis.conf
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 30s
      retries: 3
    restart: unless-stopped
  postgres:
    image: postgres
    container_name: outline-postgres
    hostname: outline-postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
networks: {}
```


.env

```
POSTGRES_USER='user'
POSTGRES_PASSWORD='pass'
POSTGRES_DB='outline'
DATABASE_URL='postgres://user:pass@outline-postgres:5432/outline'
REDIS_URL='redis://outline-redis:6379'
SECRET_KEY=d1155bc02c5bfd6b2a4c3313113b0b5f0360366aa3b68c56c5299bc4da4efdf8
UTILS_SECRET=14fec600b3d8b3524421785aef5711805a0a93d21f9ca7f251de88b675862eb
URL=https://notes.domain.com
PORT=3000
GOOGLE_CLIENT_ID=XXXXXXXXXXXX-l2ngjtdpf1ptn3injriub62i425otl1n.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=GOCSPX-oeEEYLC-XXXXXXXX

SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_USERNAME=test@gmail.com
SMTP_PASSWORD=qwbe avlw xxxx xxxx
SMTP_FROM_EMAIL=test@gmail.com
SMTP_REPLY_EMAIL=test@gmail.com
SMTP_TLS_CIPHERS=SSLv3
SMTP_SECURE=true
```
