### DISCUSSION TITLE
Pingvin: store data on a NAS?

### DISCUSSION THREAD

**Discussion by Stooovie** [community-scripts/ProxmoxVE#4260] [Q&A] [answered]
Hi, I'd like to have Pingvin use my NAS to store the data. I see in the [documentation](https://stonith404.github.io/pingvin-share/setup/configuration) I need to adjust the config.yaml to do that (adding DATA_DIRECTORY there), but it doesn't work. Data still store at `/opt/pingvin-share/backend/data`. 

I also tried to adjust the docker compose yml like this, but that didn't work either as the install is apparently not using Docker:

```
services:
  pingvin-share:
    image: stonith404/pingvin-share # or ghcr.io/stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TRUST_PROXY=false # Set to true if a reverse proxy is in front
    volumes:
      - "/media/Public/pingvin:/opt/app/backend/data"
      - "/media/Public/pingvin/images:/opt/app/frontend/public/img"
    #      - "./config.yaml:/opt/app/config.yaml" # Add this line, if needed
```

My NAS folder is mounted via fstab at /media/Public/pingvin

Any more tips? Thanks!
