### DISCUSSION TITLE
Big Breaking Changes @ Zigbee2MQTT

### DISCUSSION THREAD

**Discussion by MickLesk** [community-scripts/ProxmoxVE#660] [Announcements]
Hi,

there are a massive breaking change into zigbee2mqtt. I work on an new Script for this, but at first you can do following:

Checkout:
https://github.com/Koenkk/zigbee2mqtt/discussions/24198

1.) Install pnpm
```bash
npm install -g pnpm
```

2.) Do an Update of your config
```bash
systemctl stop zigbee2mqtt
mkdir -p /opt/z2m_backup
cp -r /opt/zigbee2mqtt/data/* /opt/z2m_backup
```

3.) Change Configuration of configuration yaml
```bash
nano /opt/zigbee2mqtt/data/configuration.yaml
```
add here in the right sections: 
```yaml
advanced:
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
```

4.) Check if your Adapter is correct configured (i had the same issue)
```bash
nano /opt/zigbee2mqtt/data/configuration.yaml
```

check this part:
```yaml
serial:
  port: /dev/ttyACM0
  adapter: zstack # <-- Add this line
```

ive used zstack, you can check it here: https://github.com/Koenkk/zigbee2mqtt/discussions/24364

5.) go into main path and enter "./update.sh"
```bash
cd /opt/zigbee2mqtt
./update.sh
```

6.) if all is correctly deployed, you can do an testrun
```
cd /opt/zigbee2mqtt && pnpm start
```
=> if it works, fine, update done

7.) Edit Service for Zigbee2MQTT
```bash
nano /etc/systemd/system/zigbee2mqtt.service
```

change "/usr/bin/npm start" to "/usr/bin/pnpm start" In ExecStart and start the service
```bash
systemctl daemon-reload
systemctl start zigbee2mqtt
```
