### ISSUE TITLE
Zigbee2mqtt - install OK but can't access to web interface

### ISSUE THREAD

**Issue by Thiiib** [community-scripts/ProxmoxVE#1274]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Zigbee2MQTT

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/zigbee2mqtt.sh)"

### 📝 Provide a clear and concise description of the issue.

Hi all

I managed to install it perfectly, it connected to my network .... but can't access to it
when looking in the console it show an IP
![proxmox_zigbee2mqtt_ip](https://github.com/user-attachments/assets/f54edfdd-64a1-4bdd-9a2f-12a3fb459ed7)
when looking in proxmox... no IP
![proxmox_zigbee2mqtt_NO-ip](https://github.com/user-attachments/assets/01629e22-2ab2-48ca-8313-2c19374667e1)

Let me know if i can help... I looked at /etc/network/interfaces and looks ok

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Launched the script, let him installed and try to acceed to the platform using IP:9442

### ❌ Paste the full error output (if available).

I don't have specific error message, just can't connect to the platform using IP:9442

**Comment by MickLesk** [comment]
Cant reproduce this. Whats the Output of Service File?

**Comment by MickLesk** [comment]
have you created the configuration.yaml and co?

Needed for working ui

![image](https://github.com/user-attachments/assets/482b4dd7-5c79-4706-9430-28ea6b7c4497)

**Comment by Thiiib** [comment]
> have you created the configuration.yaml and co?
> 
> Needed for working ui
> 
> ![image](https://private-user-images.githubusercontent.com/47820557/400341799-482b4dd7-5c79-4706-9430-28ea6b7c4497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxOTU0OTAsIm5iZiI6MTczNjE5NTE5MCwicGF0aCI6Ii80NzgyMDU1Ny80MDAzNDE3OTktNDgyYjRkZDctNWM3OS00NzA2LTk0MzAtMjhlYTZiN2M0NDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDIwMjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OWJlNzRhMmM3MjVhYTZkMjg3NjIwNWQ0NGI1NjVmOWVhMjNiN2U1ZmNlZmNkMTlhMzdmNjIxYjk1OGU3MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pWS4dPq2V7xc-dgWES1UAeDwm2X_56PsJ2RqpPkXbi4)

Hi

Thank's for your reply

Unfortunately it doesn't works... 

1. I added my USB device to the container but the number of the device change at each reboot, I tried, in the container configuration, to map using the /dev/serial/id but KO, i tried also /dev/ttyACM0 but KO

2. If i use the ID checking, before launching the container, the ID of the USB device in proxmox shell, I manage to launch the container and to edit the configuration file but restart doesn't allow me to connect... 

Here is the file as I modified it, 
![promox-VM-zigbee2mqtt-configyaml_light](https://github.com/user-attachments/assets/7e51825b-bfc7-4226-afd8-0985a8cb9e4d)

and how it looks after a restart 
![promox-VM-zigbee2mqtt-configyaml_light_afterreboot](https://github.com/user-attachments/assets/e38a7cf5-69b3-4a9f-824d-ad28551cbd72)

but I can't connect to 192.168.68.105:9442

btw I don't know what should be the "user" and "password" in the configuration file ?

**Comment by MickLesk** [comment]
Space in Server. Stop Service cd into folder and pnpm start for more Output

**Comment by Thiiib** [comment]
> Space in Server. Stop Service cd into folder and pnpm start for more Output

It's what you expected ?

`root@zigbee2mqtt:/opt/zigbee2mqtt# cd /opt/zigbee2mqtt/ && npm start

> zigbee2mqtt@2.0.0 start
> node index.js

Starting Zigbee2MQTT without watchdog.
[2025-01-07 22:02:38] info:     z2m: Logging to console, file (filename: log.log)
[2025-01-07 22:02:38] info:     z2m: Starting Zigbee2MQTT version 2.0.0 (commit #unknown)
[2025-01-07 22:02:38] info:     z2m: Starting zigbee-herdsman (3.2.1)
[2025-01-07 22:02:38] info:     z2m: zigbee-herdsman started (resumed)
[2025-01-07 22:02:38] info:     z2m: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":120,"product":0,"revision":"0x26780700","transportrev":0},"type":"ConBee2/RaspBee2"}'
[2025-01-07 22:02:38] info:     z2m: Currently 0 devices are joined.
[2025-01-07 22:02:38] info:     z2m: Connecting to MQTT server at mqtt://192.168.68.105:1883
[2025-01-07 22:02:38] error:    z2m: MQTT failed to connect, exiting... (connect ECONNREFUSED 192.168.68.105:1883)
[2025-01-07 22:02:38] info:     z2m: Stopping zigbee-herdsman...
[2025-01-07 22:02:38] info:     z2m: Stopped zigbee-herdsman`

It looks it don't manage to connect to mqtt server ?

**Comment by Thiiib** [comment]
I tried to install another container with mqtt and now the problem is connecting the adapter

```
root@zigbee2mqtt:~# cd /opt/zigbee2mqtt/ && npm start

> zigbee2mqtt@2.0.0 start
> node index.js

Starting Zigbee2MQTT without watchdog.
[2025-01-07 22:39:56] info:     z2m: Logging to console, file (filename: log.log)
[2025-01-07 22:39:56] info:     z2m: Starting Zigbee2MQTT version 2.0.0 (commit #unknown)
[2025-01-07 22:39:56] info:     z2m: Starting zigbee-herdsman (3.2.1)
[2025-01-07 22:39:56] error:    z2m: Error while starting zigbee-herdsman
[2025-01-07 22:39:56] error:    z2m: Failed to start zigbee-herdsman
[2025-01-07 22:39:56] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-01-07 22:39:56] error:    z2m: Exiting...
[2025-01-07 22:39:56] error:    z2m: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/.pnpm/zigbee-herdsman@3.2.1/node_modules/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:208:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/.pnpm/@serialport+stream@12.0.0/node_modules/@serialport/stream/dist/index.js:82:22)
    at /opt/zigbee2mqtt/node_modules/.pnpm/@serialport+stream@12.0.0/node_modules/@serialport/stream/dist/index.js:118:18
```

Here is my yaml config file
```

  GNU nano 7.2                                                                          /opt/zigbee2mqtt/data/configuration.yaml                                                                                    
homeassistant:
  enabled: true
frontend:
  enabled: true
  port: 9442
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.68.110:1883'
  version: 4
  user: mqtt-user
  password: mqtt-pwd
  keepalive: 60
  reject_unauthorized: true
advanced:
  network_key:
    - 204
    - 204
    - 10
    - 140
    - 253
    - 199
    - 137
    - 241
    - 67
    - 30
    - 152
    - 113
    - 116
    - 191
    - 218
    - 149
  pan_id: 27820
  channel: 20
serial:
  adapter: deconz
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2699176-if00
version: 4

```
