### ISSUE TITLE
Internal Error when configuring streams in NPM LXC installation

### ISSUE THREAD

**Issue by akhdanfadh** [community-scripts/ProxmoxVE#2484]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

nginxproxymanager.sh

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/nginxproxymanager.sh)"

### 📝 Provide a clear and concise description of the issue.

When attempting to configure streams in Nginx Proxy Manager (NPM) LXC, the UI consistently returns an "Internal Error" message. The system logs indicate a `structuredClone is not defined` error, probably a potential Node.js version compatibility issue(?)

### ⚙️ What settings are you using?

- [ ] Default Settings
- [x] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. Install NPM in a Proxmox LXC container using the community scripts
2. Navigate to Streams configuration on the NPM web interface
3. Configure any new stream, for example:
> Incoming Port: 25565
> Forward Host: crafty.home.arpa
> Forward Port: 25565
> TCP Forwarding enabled
4. Click Save

### Expected Behavior:

![Image](https://github.com/user-attachments/assets/e25b7f53-09b0-42db-84c7-cdba184306df)

### Actual Behavior:

![Image](https://github.com/user-attachments/assets/55873188-b3a3-420a-9176-657ea8541769)

### ❌ Paste the full error output (if available).

System logs (`journalctl -u npm -f`):
`Feb 19 07:25:29 nginx-manager node[3594]: [2/19/2025] [7:25:29 AM] [Express  ] › ⚠  warning   structuredClone is not defined`

### 🖼️ Additional context (optional).

1. Issue has been verified on fresh NPM LXC installation. The only change from default settings was the configuration of VLAN during LXC creation and disabling IPv6, which was necessary for network connectivity in my environment. All other settings were left at their defaults.
2. Tested with different stream configurations (Minecraft/Crafty server [ports](https://www.reddit.com/r/nginx/comments/jm2hyg/minecraft_server_on_nginx_proxy_manager_question/), RustDesk [ports](https://github.com/community-scripts/ProxmoxVE/discussions/2388#discussioncomment-12241886)) - same error persists
3. HOWEVER, it was SUCCESSFULLY tested on a fresh Alpine Docker LXC created using the proxmox script with the following docker-compose configuration:
```yaml
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: "host"
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
```
