### ISSUE TITLE
frigate installer no longer installs open-vino stuff

### ISSUE THREAD

**Issue by anishp55** [community-scripts/ProxmoxVE#294]
### Please verify that you have read and understood the guidelines.

yes.

### A clear and concise description of the issue.

openvino assets are not installed

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

none working install
![image](https://github.com/user-attachments/assets/a672dc2a-89d1-46db-8c0c-0ef11ece858a)
old working install
![image](https://github.com/user-attachments/assets/00dd9946-3fc4-483d-932d-6f5586eaf7df)

we can see the openvino-model directory 

### Please provide detailed steps to reproduce the issue.

install frigate with the latest install script and configure GPU detection
`bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/frigate.sh)"`

configure the GPU detector and point it to an openvino model 

```
detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
```

restart frigate and check logs

> OpenVino model file /openvino-model/FP16/ssdlite_mobilenet_v2.xml not found.

**Comment by remz1337** [comment]
What GPU are you using? Can you share your LXC config please?

Also, did you use my fork that has Nvidia GPU support? because if yes, it's normal that open-vino models don't get built, as it uses TensorRT models

```
detectors:
  tensorrt:
    type: tensorrt
#    device: 0
model:
  path: /config/model_cache/tensorrt/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```
