### ISSUE TITLE
Frigate openvino

### ISSUE THREAD

**Issue by joaopequeno-git** [community-scripts/ProxmoxVE#2949]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Frigate

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/frigate.sh)"

### 📝 Provide a clear and concise description of the issue.

After using the script i'm having issues using the openvino.
Its should be there the files, but when i change the config, i always get errors and the openvino-model folder is not here.

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🔄 Steps to reproduce the issue.

when adding this to the config:

```
detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
```

### ❌ Paste the full error output (if available).

![Image](https://github.com/user-attachments/assets/a3401b2e-e8c4-42e5-8c85-65852deef572)

**Comment by tremor021** [comment]
why are you adding that? its already configured by install script:

```
 cat <<EOF >>/config/config.yml
detectors:
  ov:
    type: openvino
    device: CPU
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
EOF
```
