### ISSUE TITLE
Slskd fails to start due to YAML config misconfiguration

### ISSUE THREAD

**Issue by shunakiyama** [community-scripts/ProxmoxVE#4649]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

slskd

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/slskd.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📝 Provide a clear and concise description of the issue.

While using the slskd LXC container script the slskd service will fail to start as it cannot find the picture described in the `soulseek` yaml segment:
```
soulseek:
   address: vps.slsknet.org
   port: 2271
   username: ~
   password: ~
   description: |
     A slskd user. https://github.com/slskd/slskd
   picture: path/to/slsk-profile-picture.jpg
```
Default picture is not provided with the container making it fail while at starting the service. Commenting out the `picture` parameter will circumvent the issue.

I recomend not setting this by default and let the user change it.

### 🔄 Steps to reproduce the issue.

1. Install the LXC container with provided bash script
2. Start the container
3. The slskd service will fail to start here and while running `sudo systemctl restart slskd`

### ❌ Paste the full error output (if available).

```
May 12 19:33:39 slskd slskd[136]: Invalid configuration:
May 12 19:33:39 slskd slskd[136]:   Soulseek:
May 12 19:33:39 slskd slskd[136]:     The Picture field specifies a non-existent file '/opt/slskd/path/to/slsk-profile-picture.jpg'.
May 12 19:33:39 slskd systemd[1]: slskd.service: Deactivated successfully.
May 12 19:33:39 slskd systemd[1]: slskd.service: Scheduled restart job, restart counter is at 1.
```
