### ISSUE TITLE
Broken dashboard on alpine-traefik configuration file

### ISSUE THREAD

**Issue by Redplcs** [community-scripts/ProxmoxVE#4825]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

alpine-traefik

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/alpine-traefik.sh)"

### ⚙️ What settings are you using?

- [ ] Default Settings
- [x] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Alpine

### 📝 Provide a clear and concise description of the issue.

I've spend whole day trying to enable dashboard that somehow does not returns anything. Browser drops closed connection, so I've managed to check the configuration file and found out that dashboard listens on 8080 under localhost. My container gets ip from dhcp and has other ip address, not localhost. I've run `netstat -tuln` and it showed that 80 and 443 listens on `:::80` and `:::443`, but the dashboard itself under `localhost:8080`. I don't think this is a correct behaviour when I was agreed with enabling dashboard and didn't expect that it will be listen inside of lxc container.

Is yaml file correct and this behavior is meant to be or not?

Also `traefik --configFile=/etc/traefik/traefik.yaml` didn't worked to reload configuration. I had to reboot whole container

### 🔄 Steps to reproduce the issue.

- Run script using this configuration file: 
```
# alpine-traefik Configuration File
# Generated on Mon May 26 11:10:27 PM MSK 2025

CT_TYPE="1"
DISK_SIZE="1"
CORE_COUNT="1"
RAM_SIZE="512"
HN="traefik"
BRG="vmbr0"
APT_CACHER_IP="none"
DISABLEIP6="yes"
PW="none"
SSH="no"
SSH_AUTHORIZED_KEY=""
VERBOSE="no"
TAGS="alpine"
VLAN="none"
MTU="1500"
GATE="none"
SD="none"
MAC="none"
NS="none"
NET="dhcp"
```
- Try to get into dashboard under 'ip address given by dhcp:8080/dashboard/'
- Live with pain

### ❌ Paste the full error output (if available).

Traefik logs are empty

**Comment by Redplcs** [comment]
I'm not familiar with traefik. I know basis of reverse proxy, but never worked with them

**Comment by Redplcs** [comment]
@tremor021 I think it's because that repo is hidden. I thought this will work

```
# alpine-traefik Configuration File
# Generated on Mon May 26 11:10:27 PM MSK 2025

CT_TYPE="1"
DISK_SIZE="1"
CORE_COUNT="1"
RAM_SIZE="512"
HN="traefik"
BRG="vmbr0"
APT_CACHER_IP="none"
DISABLEIP6="yes"
PW="none"
SSH="no"
SSH_AUTHORIZED_KEY=""
VERBOSE="no"
TAGS="alpine"
VLAN="none"
MTU="1500"
GATE="none"
SD="none"
MAC="none"
NS="none"
NET="dhcp"
```

**Comment by Redplcs** [comment]
Yea. The traefik yaml wasn't even changed. The cli asked would i like to add dashboard and i said yes. After that i've tried to connect into it and browser said `closed connection` or something like that. i've checked all opened ports and found out that it listens on localhost. I think it's the problem with configuration file that script generated

**Comment by Redplcs** [comment]
This is what helper script generates for static configuration

```
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
  traefik:
    address: 'localhost:8080'

api:
  insecure: true
  dashboard: true

ping: {}

#certificatesResolvers:
#  sample:
#    acme:
#      email: ''
#      storage: traefik/acme/account
#      dnsChallenge:
#        provider: cloudflare
#        delayBeforeCheck: 10
```
